"""Report and README generation utilities."""

from __future__ import annotations

import json
import logging
from pathlib import Path
from typing import Any

import pandas as pd

logger = logging.getLogger(__name__)


def save_json(obj: Any, path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as handle:
        json.dump(obj, handle, indent=2, default=str)
    logger.info("Saved JSON %s", path)


def _fmt_metric(metrics: dict[str, Any] | None, key: str) -> str:
    if not metrics or key not in metrics:
        return "N/A"
    val = metrics[key]
    if isinstance(val, float):
        return f"{val:.4f}"
    return str(val)


def write_final_report(
    paths: Any,
    summary: dict[str, Any],
) -> Path:
    """Write reports/final_report.md as a short research paper."""
    xgb_test = summary.get("xgboost_metrics", {}).get("metrics_test", {})
    xgb_val = summary.get("xgboost_metrics", {}).get("metrics_val", {})
    xgb_non = summary.get("non_overlapping_test_metrics", {})
    catalog = summary.get("catalog", {})
    epsilons = summary.get("epsilons", {})
    shap_top = summary.get("shap", {}).get("top_features", [])[:10]
    ablation = summary.get("ablation_table")
    horizon = summary.get("horizon_table")

    shap_lines = "\n".join(
        f"- `{r['feature']}`: mean |SHAP| = {r['mean_abs_shap']:.6f}"
        for r in shap_top
    ) or "- Pending / unavailable"

    ablation_md = (
        ablation.to_markdown(index=False)
        if isinstance(ablation, pd.DataFrame) and len(ablation)
        else "_Ablation results unavailable._"
    )
    horizon_md = (
        horizon.to_markdown(index=False)
        if isinstance(horizon, pd.DataFrame) and len(horizon)
        else "_Horizon results unavailable._"
    )

    text = f"""# Explainable Machine Learning for Short-Term Bitcoin Price Movement Prediction Using Nobitex Limit Order Book Data

## 1. Abstract

This study investigates whether Limit Order Book (LOB) microstructure features from Nobitex BTCIRT snapshots can predict short-horizon mid-price direction (DOWN / STABLE / UP). We engineer stationary imbalance, liquidity, depth, volatility, order-flow proxy, and trade features; train chronological baselines and tree ensembles (XGBoost primary, CatBoost challenger); and explain predictions with TreeSHAP. The dataset contains snapshots rather than full event streams; OFI features are therefore snapshot proxies. Results below are generated by the reproducible pipeline.

## 2. Introduction

High-frequency LOB state encodes short-lived supply/demand imbalances. We ask whether these signals remain informative for BTCIRT on Nobitex at horizons of 10–60 seconds under strict temporal validation and explainability constraints.

## 3. Research Questions

1. Can LOB information predict short-term BTCIRT mid-price direction?
2. Which microstructure variables matter most for UP, DOWN, and STABLE?
3. Are explanations stable across time, liquidity, and volatility regimes?
4. How much value do imbalance, liquidity, temporal, OFI-proxy, and trade families add?

## 4. Related-work Positioning

Classical microstructure (spread, depth, imbalance, microprice) and Cont-style order-flow imbalance motivate our feature set. Unlike DeepLOB-style neural approaches, this version stays CPU-friendly with gradient-boosted trees and TreeSHAP explanations.

## 5. Dataset

- Exchange: Nobitex
- Symbol: BTCIRT
- Raw rows (all symbols): {catalog.get('total_rows', 'N/A')}
- BTCIRT rows retained: {catalog.get('btcirt_rows', 'N/A')} ({catalog.get('pct_retained', 'N/A')}%)
- Date range: {catalog.get('btcirt_min_timestamp', 'N/A')} → {catalog.get('btcirt_max_timestamp', 'N/A')}
- Unique dates: {catalog.get('btcirt_unique_dates', 'N/A')}

Raw JSON columns (`data`, `asks`, `bids`, `last_trade`) are unused because flattened LOB columns are complete.

## 6. Data Cleaning

Quality checks cover missing values, infinite values, non-positive prices, negative quantities, crossed/locked books, and unsorted levels. Duplicate timestamps use a deterministic keep-last rule. Observed median snapshot gaps are large relative to five seconds; therefore **5-second grid alignment is not applied**. Label matching uses a widened tolerance documented in `reports/metrics/data_quality.json`.

## 7. Target Construction

Primary horizon: 30 seconds (robustness: 10s, 60s). Future mid-price is the median near \(t+h\) (with tolerance fallback). Classes use training-only epsilon:

| Horizon | Epsilon (bps) |
|---------|---------------|
| 10s | {epsilons.get('10s', 'N/A')} |
| 30s | {epsilons.get('30s', 'N/A')} |
| 60s | {epsilons.get('60s', 'N/A')} |

## 8. Feature Methodology

Features include relative spread, multi-level depth and OBI, weighted OBI, microprice edge, historical returns, realized volatility, snapshot OFI proxies, optional trade activity, and cyclical time. All rolling/lagged features are backward-looking.

## 9. Models

Baselines: majority class, previous direction, OBI rule, multinomial logistic regression. Primary: XGBoost (`multi:softprob`). Challenger: CatBoost. No neural networks in this version.

## 10. Validation Design

Chronological date split (60/20/20) with purge intervals. Anchored walk-forward folds inside train+validation. Final test untouched during tuning. Metrics reported on full test and non-overlapping (~30s) test subsets.

## 11. Results

### XGBoost validation

- Macro F1: {_fmt_metric(xgb_val, 'macro_f1')}
- Balanced accuracy: {_fmt_metric(xgb_val, 'balanced_accuracy')}
- Log loss: {_fmt_metric(xgb_val, 'log_loss')}

### XGBoost full test

- Macro F1: {_fmt_metric(xgb_test, 'macro_f1')}
- Balanced accuracy: {_fmt_metric(xgb_test, 'balanced_accuracy')}
- Log loss: {_fmt_metric(xgb_test, 'log_loss')}
- Accuracy: {_fmt_metric(xgb_test, 'accuracy')}
- F1 DOWN / STABLE / UP: {_fmt_metric(xgb_test, 'f1_DOWN')} / {_fmt_metric(xgb_test, 'f1_STABLE')} / {_fmt_metric(xgb_test, 'f1_UP')}

### Non-overlapping test

- Macro F1: {_fmt_metric(xgb_non, 'macro_f1')}
- Balanced accuracy: {_fmt_metric(xgb_non, 'balanced_accuracy')}

**Interpretation.** Compare full vs non-overlapping metrics to assess sensitivity to label overlap from dense sampling. Per-class F1 shows which directions are harder; STABLE is shaped by the epsilon quantile and snapshot sparsity.

Best hyperparameters: `{summary.get('best_hyperparameters', {})}`

## 12. Explainability Results

TreeSHAP global importance (top features):

{shap_lines}

**Disclaimer:** SHAP explains how the model uses features. SHAP does not prove causal relationships.

Regime stability tables are saved in `reports/tables/shap_stability_results.csv`.

## 13. Ablation Study

{ablation_md}

Ablation tests whether high SHAP features also carry out-of-sample predictive value when removed as families.

## 14. Robustness Analysis

{horizon_md}

Each horizon uses its own training-fitted epsilon. Horizon differences reflect both predictability decay and label construction under sparse snapshots.

## 15. Limitations

- Snapshots ≠ full order-event stream; OFI is a proxy.
- Median inter-snapshot gaps ≈ tens of seconds, so 10s/30s horizons often resolve near the next snapshot.
- BTCIRT/Nobitex microstructure may not generalize.
- Prediction ≠ executable trading profits after fees/slippage.
- CPU-friendly models omit deep sequence architectures.

## 16. Conclusion

The pipeline provides a transparent, temporally honest benchmark for short-horizon BTCIRT direction prediction from LOB snapshots, with SHAP-based interpretation and ablation/horizon stress tests.

## 17. Future Work

Event-level OFI reconstruction, longer samples, cost-aware decision thresholds, and cross-market transfer tests.

---
Generated automatically from pipeline outputs. Figures live in `reports/figures/`.
"""
    out = paths.reports / "final_report.md"
    out.write_text(text, encoding="utf-8")
    logger.info("Wrote final report %s", out)
    return out


def write_readme(paths: Any, summary: dict[str, Any]) -> Path:
    """Write/update professional README with actual results (or pending markers)."""
    executed = bool(summary.get("pipeline_completed"))
    catalog = summary.get("catalog", {})
    xgb_test = summary.get("xgboost_metrics", {}).get("metrics_test", {})
    xgb_val = summary.get("xgboost_metrics", {}).get("metrics_val", {})
    xgb_non = summary.get("non_overlapping_test_metrics", {})
    epsilons = summary.get("epsilons", {})
    shap_top = summary.get("shap", {}).get("top_features", [])[:8]

    results_section = """## 13. Experimental Results

> **Status: PENDING** — Run `python -m src.pipeline --config configs/project_config.yaml` to populate metrics from actual execution. Do not treat placeholder values as real.
"""
    if executed:
        shap_md = "\n".join(
            f"| `{r['feature']}` | {r['mean_abs_shap']:.6f} |" for r in shap_top
        )
        results_section = f"""## 13. Experimental Results

Results below are produced by executing the pipeline (seed={summary.get('random_seed', 42)}).

### Data retained
- Total raw rows: **{catalog.get('total_rows')}**
- BTCIRT rows: **{catalog.get('btcirt_rows')}** ({catalog.get('pct_retained'):.4f}%)
- Date range: `{catalog.get('btcirt_min_timestamp')}` → `{catalog.get('btcirt_max_timestamp')}`
- Unique dates: **{catalog.get('btcirt_unique_dates')}**
- Engineered features: **{summary.get('n_features')}**
- Epsilon 10s / 30s / 60s (bps): **{epsilons.get('10s')}** / **{epsilons.get('30s')}** / **{epsilons.get('60s')}**

### Best model: XGBoost
- Best hyperparameters: `{summary.get('best_hyperparameters')}`
- Validation Macro F1: **{_fmt_metric(xgb_val, 'macro_f1')}**
- Test Macro F1: **{_fmt_metric(xgb_test, 'macro_f1')}**
- Test Balanced Accuracy: **{_fmt_metric(xgb_test, 'balanced_accuracy')}**
- Test Log Loss: **{_fmt_metric(xgb_test, 'log_loss')}**
- Non-overlapping Test Macro F1: **{_fmt_metric(xgb_non, 'macro_f1')}**

### Top SHAP features
| Feature | Mean |SHAP| |
|---------|-------------|
{shap_md}

![Global SHAP](reports/figures/shap_global_importance.png)
![Model comparison](reports/figures/model_comparison_macro_f1.png)
![Confusion](reports/figures/xgb_normalized_confusion_test.png)
![Ablation](reports/figures/ablation_comparison.png)
![Horizons](reports/figures/horizon_comparison.png)
"""

    readme = f"""# Explainable Machine Learning for Short-Term Bitcoin Price Movement Prediction Using Nobitex Limit Order Book Data

## 1. Abstract

This repository implements a reproducible research pipeline that predicts short-term **BTCIRT** mid-price direction from Nobitex Limit Order Book snapshots using CPU-friendly gradient boosting (XGBoost) and TreeSHAP explainability. The task is three-class classification (`DOWN`, `STABLE`, `UP`) at a primary 30-second horizon, with robustness checks at 10 and 60 seconds.

## 2. Research Questions

1. Can LOB information predict short-term BTCIRT mid-price direction?
2. Which microstructure variables matter most for UP, DOWN, and STABLE moves?
3. Are model explanations stable across time, liquidity, and volatility regimes?
4. How much predictive value do imbalance, liquidity, temporal, OFI-proxy, and trade features add?

## 3. Motivation

Short-horizon crypto prices respond to visible book imbalance, liquidity, and order-flow pressure. Transparent tree models plus SHAP allow economically readable attributions without GPU-heavy deep LOB architectures.

## 4. Dataset Description

- Source file: `data/raw/market_data_clean_nobitex.csv` (**not committed**)
- Filter: `exchange == nobitex`, `symbol == BTCIRT` (normalized)
- Multi-market raw CSV; only BTCIRT retained

### Important caveats
- Data are **snapshots**, not a complete order-event stream.
- **OFI is a snapshot-based proxy**, not true event OFI.
- Analysis is specific to **BTCIRT on Nobitex** and may not generalize.
- **SHAP is not causal**.
- **Prediction ≠ trading profitability**.

## 5. Data Schema

Expected columns include identifiers (`id`, `timestamp`, `exchange`, `symbol`), flattened LOB levels 1–8 (`asks_price_*`, `asks_qty_*`, `bids_price_*`, `bids_qty_*`), and `last_trade_price` / `last_trade_qty`. JSON-like columns (`data`, `asks`, `bids`, `last_trade`) are unused when flattened fields are complete.

## 6. Data-Quality Summary

See `reports/metrics/data_quality.json` and `reports/tables/data_quality_summary.csv` after running the pipeline. Gaps, crossed books, and unsorted levels are counted explicitly—not silently ignored.

## 7. Target Definition

Future mid-price near \(t+h\) (median in a smoothing window, with tolerance fallback under sparse sampling). Future log-return in bps; classes via training-only epsilon targeting ~35% STABLE.

## 8. Feature Engineering

Economically motivated stationary features:

| Feature family | Examples | Meaning |
|----------------|----------|---------|
| Liquidity | `relative_spread_bps` | Cost of immediacy / thinness |
| Depth | `log_*_depth_k` | Displayed size near touch |
| Imbalance | `obi_k`, `weighted_obi` | Bid vs ask pressure |
| Microprice | `microprice_edge_bps` | Size-weighted fair-price displacement |
| Order flow | `ofi_proxy_*`, `normalized_ofi_*` | Snapshot OFI proxy |
| Dynamics | `return_*s`, `delta_*` | Recent mid/imbalance changes |
| Volatility | `volatility_*s` | Realized short-horizon risk |
| Trade | `trade_imbalance_*`, `time_since_last_trade` | Optional last-trade activity |
| Time | `hour_sin/cos` | Intraday seasonality |

## 9. Model Methodology

- Baselines: majority, previous direction, OBI rule, multinomial logistic regression
- Primary: XGBoost (`multi:softprob`, `tree_method=hist`)
- Challenger: CatBoost
- No neural nets / GPU methods in this version

## 10. Temporal Validation

Chronological **date** split 60/20/20 + purge gap. Walk-forward folds inside train+val. Test set frozen until final evaluation. Metrics on full and non-overlapping test subsets.

## 11. Evaluation Metrics

Primary: **Macro F1**. Also: balanced accuracy, per-class PR/F1, log loss, MCC, Brier, OvR ROC-AUC, confusion matrices, day-bootstrap CIs when feasible.

## 12. Financial Feature Meanings

- **Spread**: difference between best ask and bid; relative spread in bps normalizes by mid.
- **Depth**: cumulative displayed size; log depth stabilizes heavy tails.
- **OBI**: normalized bid−ask depth; positive values indicate buy-side dominance.
- **Weighted OBI**: exponentially emphasizes near-touch levels.
- **Microprice**: size-weighted combination of best quotes; edge vs mid is a short-horizon signal.
- **OFI proxy**: Cont-style best-level contribution from consecutive **snapshots**.
- **Volatility**: sqrt of summed squared snapshot log-returns over a time window.

{results_section}

## 14. SHAP Explainability Findings

See `reports/final_report.md` and `reports/tables/shap_*.csv`. Explanations describe model behavior, not causality.

## 15. Feature Ablation Findings

See `reports/tables/ablation_results.csv` and `reports/figures/ablation_comparison.png`.

## 16. Horizon Robustness Findings

See `reports/tables/horizon_comparison.csv`.

## 17. Main Figures

Generated under `reports/figures/` (EDA, metrics, SHAP, ablation, horizons).

## 18. Interpretation of Results

Interpret Macro F1 relative to majority/OBI baselines. Inspect whether gains survive non-overlapping evaluation and whether SHAP-important families also hurt performance when ablated.

## 19. Limitations

Snapshot sparsity, market specificity, non-causal SHAP, and cost-unaware classification objectives.

## 20. Ethical and Financial Disclaimer

This project is for research and education only. It is **not** investment advice. Cryptocurrency trading involves substantial risk of loss. Do not deploy without independent validation, compliance review, and realistic transaction-cost modeling.

## 21. Reproduction Instructions

```bash
cd explainable-btcirt-lob
python -m venv .venv
source .venv/bin/activate
pip install -r requirements.txt
# Place market_data_clean_nobitex.csv in data/raw/
make all
# or:
python -m src.pipeline --config configs/project_config.yaml
pytest -q
```

## 22. Project Structure

See repository tree under `src/`, `notebooks/`, `configs/`, `reports/`, and `tests/`.

## 23. Future Work

Event-level reconstruction, multi-venue studies, and decision-focused evaluation under fees.

## 24. Citation

```bibtex
@software{{explainable_btcirt_lob,
  title  = {{Explainable ML for Short-Term BTCIRT LOB Prediction}},
  year   = {{2026}},
  note   = {{Nobitex BTCIRT snapshot study}}
}}
```
"""
    out = paths.root / "README.md"
    out.write_text(readme, encoding="utf-8")
    logger.info("Wrote README %s", out)
    return out
